/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import domain.BD;
import domain.Mail;
import domain.usuarios;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.sql.RowSetMetaData;
import javax.sql.rowset.CachedRowSet;

/**
 *
 * @author gabriel.suarez
 */
public class frmMailCliente extends javax.swing.JFrame {

    /**
     * Creates new form frmMailCliente
     */
    public frmMailCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtBody = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCCO = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtAsunto = new javax.swing.JTextField();
        send = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        txtBody.setColumns(20);
        txtBody.setLineWrap(true);
        txtBody.setRows(5);
        txtBody.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtBody);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 136, 610, 380);

        jLabel1.setText("CCO:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 10, 30, 14);

        txtCCO.setColumns(20);
        txtCCO.setLineWrap(true);
        txtCCO.setRows(5);
        txtCCO.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtCCO);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(90, 10, 530, 80);

        jLabel2.setText("ASUNTO:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 100, 60, 20);
        getContentPane().add(txtAsunto);
        txtAsunto.setBounds(90, 100, 530, 20);

        send.setText("Send");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });
        getContentPane().add(send);
        send.setBounds(10, 30, 70, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        // TODO add your handling code here:
        ArrayList pers = new ArrayList();
        String cco = txtCCO.getText().replace(",", ";");
        
        String mails [] = cco.split(";");
        
        for(int i = 0; mails.length > i; i++)
        {
            String to = mails[i];
            to = to.replace(" ", "");
            pers.add(mails[i]);
        }
        
        String bod = txtBody.getText().replace("\n", "<br>");
        
        asunto = txtAsunto.getText();
        
        Mail unM = new Mail ("", asunto, bod, "", null, pers, "CCO", miUsuario.firma);  
        
    }//GEN-LAST:event_sendActionPerformed

    public String consulta = "", usuario = "", asunto = "";
    public usuarios miUsuario;
    
    public void abrir(String sql, String usu, String asu, usuarios u)
    {
        miUsuario = u;
        consulta = sql;
        usuario = usu;
        asunto = asu;
        this.setVisible(true);
        //setLocationRelativeTo(null);
        this.setTitle("MENSAJE EN COPIA OCULTA    -    SIF ");;
        this.setMinimumSize(new Dimension(650, 600)); 
        
        cargarMails();        
        txtAsunto.setText(asunto);
        
    }    
    
    public void cargarMails()
    {
        BD unb = new BD();
        
        try
        {
            BD unB = new BD();
            CachedRowSet lista = unB.Function(consulta);
            RowSetMetaData rsmd = (RowSetMetaData)lista.getMetaData();
            
            while (lista.next())
            {
                txtCCO.setText(txtCCO.getText() + "; " + lista.getString(1));
            }
            
            txtCCO.setText(txtCCO.getText().substring(1,txtCCO.getText().length()));
            
        }
        catch (Exception ex)
        {
        }
        
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton send;
    private javax.swing.JTextField txtAsunto;
    private javax.swing.JTextArea txtBody;
    private javax.swing.JTextArea txtCCO;
    // End of variables declaration//GEN-END:variables
}
