/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dominio.ComponentesLista;
import dominio.producto;
import java.awt.Dimension;

/**
 *
 * @author sistemas
 */
public class frmABMProductos extends javax.swing.JFrame {

    /**
     * Creates new form frmABMProductos
     */
    public frmABMProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chkPeso = new javax.swing.JCheckBox();
        cmdGuardar = new javax.swing.JButton();
        cmdReset = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        txtBarra = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        cmbProductos = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        tblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProducto);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 100, 560, 390);

        jLabel1.setText("ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 30, 20);

        lblID.setText("0");
        getContentPane().add(lblID);
        lblID.setBounds(40, 10, 40, 20);

        jLabel3.setText("BARRA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 10, 50, 20);

        jLabel4.setText("CODIGO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 10, 60, 20);

        jLabel5.setText("PRODUCTO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 50, 70, 20);

        jLabel6.setText("PRECIO");
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(300, 50, 50, 20);

        chkPeso.setText("PESO");
        getContentPane().add(chkPeso);
        chkPeso.setBounds(390, 10, 60, 20);

        cmdGuardar.setBackground(new java.awt.Color(255, 51, 51));
        cmdGuardar.setText("GUARDAR");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(cmdGuardar);
        cmdGuardar.setBounds(480, 10, 90, 23);

        cmdReset.setBackground(new java.awt.Color(153, 153, 255));
        cmdReset.setText("RESET");
        cmdReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdResetActionPerformed(evt);
            }
        });
        getContentPane().add(cmdReset);
        cmdReset.setBounds(480, 50, 90, 23);
        getContentPane().add(txtCodigo);
        txtCodigo.setBounds(300, 10, 60, 20);
        getContentPane().add(txtBarra);
        txtBarra.setBounds(140, 10, 80, 20);
        getContentPane().add(txtPrecio);
        txtPrecio.setBounds(350, 50, 100, 20);

        cmbProductos.setEditable(true);
        cmbProductos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbProductos);
        cmbProductos.setBounds(80, 50, 190, 20);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 90, 560, 10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdResetActionPerformed
        // TODO add your handling code here:
        reset();
        
    }//GEN-LAST:event_cmdResetActionPerformed

    private void tblProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductoMouseClicked
        // TODO add your handling code here:
        String id = tblProducto.getModel().getValueAt(tblProducto.getSelectedRow() , 0).toString();
        producto p = new producto();
        p.cargarPorId(id);
        lblID.setText(p.id);
        txtBarra.setText(p.barra);
        txtCodigo.setText(p.codigo);
        txtPrecio.setText(p.precio);
        cmbProductos.setSelectedItem(p.nombre);
        if (p.peso.equals("1")){  chkPeso.setSelected(true);  }else{  chkPeso.setSelected(false);  }                
    }//GEN-LAST:event_tblProductoMouseClicked

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
        // TODO add your handling code here:
        producto p = new producto();
        p.id = lblID.getText();
        p.barra = txtBarra.getText();
        p.codigo = txtCodigo.getText();
        p.precio = txtPrecio.getText();
        p.nombre = cmbProductos.getSelectedItem().toString();
        if (chkPeso.isSelected()){  p.peso = "1";  }else{  p.peso = "0";  }
        p.guardar();
        reset();
        //QUITAR CUANDO ESTE OPERATIVO 
        //unC.cargarCombo("select distinct (nombre) from productos order by nombre", cmbProductos);

    }//GEN-LAST:event_cmdGuardarActionPerformed

    ComponentesLista unC = new ComponentesLista();
    public void reset()
    {
        lblID.setText("0");
        txtBarra.setText("");
        /*txtCodigo.setText("");
        txtPrecio.setText("0");
        unC.cargarCombo("select distinct (nombre) from productos order by nombre", cmbProductos);
        chkPeso.setSelected(false);*/
        unC.cargarTabla("select id, codigo, barra, nombre, peso, precio from productos order by nombre", tblProducto);
    }

    public void abrir()
    {
        this.setVisible(true);
        this.setTitle("ABM PRODUCTOS - ALMACEN");
        this.setMinimumSize(new Dimension(600, 550)); 
        reset();
        //Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/eme.png"));
        //this.setIconImage(icon);       
         //QUITAR CUANDO ESTE OPERATIVO 
        unC.cargarCombo("select distinct (nombre) from productos order by nombre", cmbProductos);

    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkPeso;
    private javax.swing.JComboBox cmbProductos;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblID;
    private javax.swing.JTable tblProducto;
    private javax.swing.JTextField txtBarra;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
