/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dominio.BD;
import dominio.ComponentesLista;
import dominio.controlador;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author sistemas
 */
public class frmMantenimientoBultos extends javax.swing.JFrame {

        public controlador miControlador;
    
    public void abrir(controlador unC)
    {
        miControlador = unC;
        this.setVisible(true);
        this.setTitle("VELMAREN - Mantenimiento Bultos");
        this.setMinimumSize(new Dimension(800, 600)); 
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/eme.png"));
        this.setIconImage(icon);   
        
        
        reset();
        
        
        
    }    
    
    public void reset()
    {
        String url = "SELECT id_bul AS ID, mercaderia_bul AS Mercaderia, aduana_bul AS Aduana, opus_bul AS Armador FROM bridge_tipobultos order by mercaderia_bul";
        
        ComponentesLista unCc = new ComponentesLista();
        unCc.cargarTabla(url, tblLista);
    }
    
    public frmMantenimientoBultos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtCodigoArm = new javax.swing.JTextField();
        txtArmador = new javax.swing.JTextField();
        btnAdd = new javax.swing.JToggleButton();
        btnModify = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLista = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jtCodigoArm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtCodigoArmKeyReleased(evt);
            }
        });
        getContentPane().add(jtCodigoArm);
        jtCodigoArm.setBounds(50, 50, 220, 20);

        txtArmador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArmadorActionPerformed(evt);
            }
        });
        getContentPane().add(txtArmador);
        txtArmador.setBounds(460, 120, 110, 20);

        btnAdd.setLabel("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(580, 120, 60, 23);

        btnModify.setLabel("Modify");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        getContentPane().add(btnModify);
        btnModify.setBounds(650, 120, 73, 23);

        tblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLista);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 160, 670, 340);

        jLabel1.setText("Codigo Armador:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(460, 90, 130, 30);

        jLabel2.setText("Buscar:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 30, 110, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String mercaderia = tblLista.getValueAt(tblLista.getSelectedRow(), 1).toString();
        String aduana = tblLista.getValueAt(tblLista.getSelectedRow(), 2).toString();
        
        String url = "INSERT INTO bridge_tipobultos (mercaderia_bul, aduana_bul, opus_bul) VALUES ('" + mercaderia + "','" + aduana  + "','" + txtArmador.getText() +  "')";
        
        BD unB = new BD();
        unB.StoreProcedure(url, "velmaren");
        JOptionPane.showMessageDialog(null, "Procesado con exito!");
        txtArmador.setText("");
        
        reset();
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtArmadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArmadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArmadorActionPerformed

    private void jtCodigoArmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCodigoArmKeyReleased
        String valor =  jtCodigoArm.getText();
        //JOptionPane.showMessageDialog(null, valor);
        String url = "SELECT id_bul AS ID, mercaderia_bul AS Mercaderia, aduana_bul AS Aduana, opus_bul AS Armador FROM bridge_tipobultos WHERE mercaderia_bul LIKE '%" + valor + "%' OR aduana_bul LIKE '%" + valor + "%' OR opus_bul LIKE '%" + valor + "%' order by mercaderia_bul"; 
        
        ComponentesLista unC = new ComponentesLista();
        unC.cargarTabla(url, tblLista);
        
        
    }//GEN-LAST:event_jtCodigoArmKeyReleased

    private void tblListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaMouseClicked
        String valor = tblLista.getValueAt(tblLista.getSelectedRow(), 3).toString();
        txtArmador.setText(valor);
    }//GEN-LAST:event_tblListaMouseClicked

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        String id = tblLista.getValueAt(tblLista.getSelectedRow(), 0).toString();
        String valor = txtArmador.getText();
        String url = "UPDATE bridge_tipobultos SET opus_bul = '" + valor + "' WHERE id_bul = '" + id + "' ";
        
        BD unB = new BD();
        unB.StoreProcedure(url, "velmaren");
        JOptionPane.showMessageDialog(null, "Procesado con exito!");
        txtArmador.setText("");
        
        reset();
    }//GEN-LAST:event_btnModifyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoBultos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoBultos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoBultos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoBultos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMantenimientoBultos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAdd;
    private javax.swing.JButton btnModify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtCodigoArm;
    private javax.swing.JTable tblLista;
    private javax.swing.JTextField txtArmador;
    // End of variables declaration//GEN-END:variables
}
